import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    loadingText: {
        flex: 1,
        textAlign: 'center',
        marginTop: 100,
        fontSize: 16,
        color: '#64748b',
    },
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    permissionTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#fff',
        marginTop: 24,
        marginBottom: 8,
    },
    permissionMessage: {
        fontSize: 16,
        color: '#e0e7ff',
        textAlign: 'center',
        marginBottom: 32,
    },
    permissionButton: {
        backgroundColor: '#fff',
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 12,
    },
    permissionButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3b82f6',
    },
    headerBlurContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
        overflow: 'hidden',
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    header: {
        paddingTop: Platform.OS === 'web' ? 24 : 60,
        paddingBottom: 24,
        paddingHorizontal: 24,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 16,
        color: '#dbeafe',
    },
    camera: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    scannerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scannerFrame: {
        width: 250,
        height: 250,
        borderWidth: 3,
        borderColor: '#fff',
        borderRadius: 24,
        backgroundColor: 'transparent',
    },
    scannerInstruction: {
        marginTop: 32,
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
        paddingHorizontal: 32,
        fontWeight: '600',
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    resultsContainer: {
        flex: 1,
        padding: 20,
        paddingTop: Platform.OS === 'web' ? 120 : 156,
    },
    resultCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    paramRow: {
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    paramLabel: {
        fontSize: 13,
        color: '#64748b',
        marginBottom: 4,
        fontWeight: '500',
    },
    paramValue: {
        fontSize: 16,
        color: '#0f172a',
        fontWeight: '600',
    },
    actionButtons: {
        flexDirection: 'row',
        padding: 20,
        gap: 12,
    },
    scanAgainButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
        borderWidth: 2,
        borderColor: '#3b82f6',
    },
    scanAgainButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3b82f6',
    },
    goButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#3b82f6',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
    },
    goButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
    },
    errorCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    errorIconContainer: {
        marginBottom: 16,
    },
    errorCardTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#dc2626',
        marginBottom: 8,
        textAlign: 'center',
    },
    errorCardMessage: {
        fontSize: 14,
        color: '#64748b',
        textAlign: 'center',
        marginBottom: 20,
    },
    contentBox: {
        width: '100%',
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        padding: 16,
        borderLeftWidth: 4,
        borderLeftColor: '#dc2626',
    },
    contentLabel: {
        fontSize: 12,
        color: '#64748b',
        marginBottom: 8,
        fontWeight: '600',
    },
    contentValue: {
        fontSize: 14,
        color: '#0f172a',
        fontWeight: '500',
        lineHeight: 20,
    },
    errorActionButtons: {
        flexDirection: 'row',
        padding: 20,
        gap: 12,
    },
    copyButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#10b981',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
    },
    copyButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
    },
    scanAgainButtonError: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
        borderWidth: 2,
        borderColor: '#3b82f6',
    },
    scanAgainButtonTextError: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3b82f6',
    },
    floatingSelectButton: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    floatingSelectButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
    },
    blurWrapper: {
        position: 'absolute',
        bottom: 24,
        left: '50%',
        marginLeft: -85,
        borderRadius: 50,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    selectedImage: {
        flex: 1,
        width: '100%',
    },
    floatingButtonContainer: {
        position: 'absolute',
        bottom: 24,
        left: '50%',
        marginLeft: -75,
        minWidth: 150,
    },
    processingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    processingText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    settingsButton: {
        position: 'absolute',
        top: Platform.OS === 'web' ? 24 : 60,
        right: 24,
        padding: 8,
        zIndex: 1,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 24,
        paddingBottom: 20,
        paddingHorizontal: 24,
        maxHeight: '95%',
        flex: 1
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#0f172a',
        flex: 1,
    },
    settingsSection: {
        flex: 1,
    },
    settingsMenu: {
        flex: 1,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        marginBottom: 12,
    },
    menuItemIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#eff6ff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    menuItemContent: {
        flex: 1,
    },
    menuItemTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
        marginBottom: 4,
    },
    menuItemDescription: {
        fontSize: 14,
        color: '#64748b',
    },
    settingsScrollView: {
        flex: 1,
    },
    settingsSectionDescription: {
        fontSize: 14,
        color: '#64748b',
        marginBottom: 20,
    },
    cameraList: {
        maxHeight: 200,
    },
    cameraOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    cameraOptionSelected: {
        backgroundColor: '#eff6ff',
        borderColor: '#3b82f6',
    },
    cameraOptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
    },
    cameraOptionText: {
        fontSize: 16,
        color: '#64748b',
        fontWeight: '500',
        flex: 1,
    },
    cameraOptionTextSelected: {
        color: '#3b82f6',
        fontWeight: '600',
    },
    selectedIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3b82f6',
    },
    noCamerasContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
    },
    noCamerasText: {
        fontSize: 16,
        color: '#64748b',
        marginTop: 12,
    },
    comingSoonContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    comingSoonTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#0f172a',
        marginTop: 16,
        marginBottom: 8,
    },
    comingSoonText: {
        fontSize: 14,
        color: '#64748b',
        textAlign: 'center',
        paddingHorizontal: 32,
    },
    aboutContainer: {
        alignItems: 'center',
        padding: 24,
        marginTop: 12,
        borderRadius: 16,
    },
    logoContainer: {
        width: 100,
        height: 100,
        marginBottom: 16,
        borderRadius: 24,
        overflow: 'hidden',
    },
    logo: {
        width: '100%',
        height: '100%',
    },
    appName: {
        fontSize: 24,
        fontWeight: '700',
        color: '#0f172a',
        marginBottom: 12,
        textAlign: 'center',
    },
    versionPill: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        marginBottom: 24,
    },
    versionText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#64748b',
    },
    appDescription: {
        fontSize: 15,
        color: '#475569',
        lineHeight: 22,
        marginBottom: 32,
        textAlign: 'center',
    },
    developerSectionCentered: {
        alignItems: 'center',
        marginBottom: 32,
    },
    developerLabel: {
        fontSize: 12,
        color: '#64748b',
        marginBottom: 4,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    developerName: {
        fontSize: 16,
        color: '#0f172a',
        fontWeight: '600',
    },
    aboutActionButtons: {
        width: '100%',
        gap: 12,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000000ff',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 12,
        gap: 8,
        width: '100%',
    },
    coffeeButton: {
        backgroundColor: '#FFDD00',
    },
    actionButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    actionButtonTextBlack: {
        fontSize: 14,
        fontWeight: '600',
        color: '#000',
    },
});
