name: Buy Me A Coffee Readme

on:
  workflow_dispatch:

jobs:
  bmac-readme:
    name: Update Buy Me A Coffee section in this repo's README
    runs-on: ubuntu-latest
    steps:
      # no longer works because API got replaced with webhooks so i will probably make a version of it myself later.
      - uses: akosbalasko/coffee-readme@main
        with:
          BUY_ME_A_COFFEE_TOKEN: ${{ secrets.BUY_ME_A_COFFEE_TOKEN }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN }}
          README: 'README.md'
          BRANCH: 'master'
